### ISSUE TITLE
🚧Fix deprecated outputs

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/DotNetGitHubActionTemplate#33]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor all of the deprecated step output setups to the new style of setting step outputs.
These changes need to be done in the _**build-status-check.yml**_ and _**unit-tests-status-check.yml**_ workflows.

### _**build-status-check.yml Change 1:**_
```diff
if ( "${{ github.base_ref }}" -eq "master") {
-  Write-Host "::set-output name=build-config::Release";
+  "build-config=Release" >> $env:GITHUB_OUTPUT;
} else { # Any other branch than master, do a debug build
-  Write-Host "::set-output name=build-config::Debug";
+  "build-config=Debug" >> $env:GITHUB_OUTPUT;
}
```

### _**build-status-check.yml Change 2:**_
```diff
get_sdk_version:
  name: Get SDK Version
  runs-on: ubuntu-latest
  outputs:
    sdk-version: ${{ steps.get-sdk-version.outputs.sdk-version }}
  steps:
    - name: Get SDK Version From Environment Variable
      id: get-sdk-version
      shell: pwsh
-      run: Write-Host "::set-output name=sdk-version::${{ env.NET_SDK_VERSION }}";
+      run: Write-Host "sdk-version=${{ env.NET_SDK_VERSION }}" >> $env:GITHUB_OUTPUT;
```

### _**unit-tests-status-check.yml Change 1:**_
```diff
if ( "${{ github.base_ref }}" -eq "master") {
-  Write-Host "::set-output name=build-config::Release";
+  "build-config=Release" >> $env:GITHUB_OUTPUT;
} else { # Any other branch than master, do a debug build
-  Write-Host "::set-output name=build-config::Debug";
+  "build-config=Debug" >> $env:GITHUB_OUTPUT;
}
```

### Acceptance Criteria

- [x] _**build-status-check.yml**_ updated
- [x] _**unit-tests-status-check.yml**_ updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
